version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-wallet-kit-orders
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php

  php:
    container_name: php-wallet-kit-orders
    restart: unless-stopped
    build: docker/php
    links:
      - postgres
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2
    container_name: postgres-wallet-kit-orders
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis-wallet-kit-orders
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ['--requirepass test123']

  ngrok:
    container_name: ngrok-wallet-kit-orders
    image: ngrok/ngrok:3
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./docker/ngrok/ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    extra_hosts:
      - "host.docker.internal:host-gateway"
